import React, { createContext, useContext, useState, useEffect } from 'react';

export const LANGUAGES = [
  { code: 'en', name: 'English', nativeName: 'English', dir: 'ltr', flag: '🇬🇧' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', dir: 'rtl', flag: '🇦🇪' },
  { code: 'ur', name: 'Urdu', nativeName: 'اردو', dir: 'rtl', flag: '🇵🇰' },
  { code: 'zh', name: 'Chinese', nativeName: '中文', dir: 'ltr', flag: '🇨🇳' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', dir: 'ltr', flag: '🇪🇸' },
  { code: 'fr', name: 'French', nativeName: 'Français', dir: 'ltr', flag: '🇫🇷' },
  { code: 'de', name: 'German', nativeName: 'Deutsch', dir: 'ltr', flag: '🇩🇪' },
  { code: 'ru', name: 'Russian', nativeName: 'Русский', dir: 'ltr', flag: '🇷🇺' },
  { code: 'tr', name: 'Turkish', nativeName: 'Türkçe', dir: 'ltr', flag: '🇹🇷' }
];

export const TRANSLATIONS = {
  en: {
    // Navigation
    nav_home: 'Home',
    nav_visa: 'Visa',
    nav_services: 'Services',
    nav_business_setup: 'Business Setup',
    nav_visa_check: 'Visa Check',
    nav_about: 'About',
    nav_blog: 'Blog',
    nav_contact: 'Contact',
    nav_consultation_btn: 'Free Consultation',
    nav_typing_sub: 'Typing & Consulting',

    // Mega Dropdown Headers & Buttons
    visa_cat_header: 'RESIDENCY AND VISAS',
    services_cat_header: 'OUR SERVICES',
    services_col1_header: 'PRO & LEGAL SERVICES',
    services_col2_header: 'PROPERTY & SUPPORT',
    services_default_title: 'Expert Support, Every Step',
    services_default_desc: 'Reliable assistance for life and business in the UAE',
    services_default_btn: 'Explore All Services',
    biz_header: 'START YOUR BUSINESS JOURNEY',
    biz_col_mainland: 'MAINLAND',
    biz_col_freezone: 'FREE ZONE',
    biz_col_offshore: 'OFFSHORE',

    // Hero Section
    hero_title_prefix: 'Fast & Reliable',
    hero_title_highlight: 'UAE Visa & Passport',
    hero_title_suffix: 'Services',
    hero_subtitle: 'Authorized assistance for 10-Year Golden Visas, Family Sponsorship, Emirates ID, BLS Indian Passport Renewals, and Business Setup in Dubai. Transparent pricing, legal auditing, and express same-day submission.',
    hero_cta_consultation: 'Book Free Consultation',
    hero_cta_calculator: 'Visa Cost Calculator',
    hero_stat_1_val: '20+',
    hero_stat_1_lbl: 'Years Experience',
    hero_stat_1_desc: 'Established presence in Dubai',
    hero_stat_2_val: '10,000+',
    hero_stat_2_lbl: 'Clients Served',
    hero_stat_2_desc: 'Expatriates, families & investors',
    hero_stat_3_val: '98%',
    hero_stat_3_lbl: 'Success Rate',
    hero_stat_3_desc: '5-Star verified client satisfaction',
    hero_stat_4_val: '15+',
    hero_stat_4_lbl: 'Govt Accreditations',
    hero_stat_4_desc: 'GDRFA • ICP • BLS • MOHRE Portals',

    // About Section
    about_badge: 'ABOUT BRIGHTLINK TYPING',
    about_title: "Dubai's Premier Government Typing & Visa Processing Center",
    about_desc_1: 'With over two decades of dedicated service in the UAE, Brightlink provides seamless, compliant, and expedited typing services for individuals, families, and multinational corporations.',
    about_desc_2: 'Our direct integration with GDRFA, ICP, Dubai Courts, and MOHRE ensures your applications are typed with zero errors and processed with priority government approvals.',
    about_point_1: 'Official GDRFA & Amer authorized typing portal',
    about_point_2: 'VIP express medical fitness & Emirates ID typing',
    about_point_3: 'Direct DED & Free Zone corporate licensing division',
    about_point_4: 'Certified MOJ legal translation & document attestation',
    about_btn_consultation: 'Schedule Expert Consultation',
    about_btn_services: 'Explore Services',

    // Services Section
    services_badge: 'COMPREHENSIVE SERVICES',
    services_title: 'Tailored Visa & Government Solutions',
    services_subtitle: 'From residency renewals to multi-million property investor visas, our accredited typing specialists guarantee full legal compliance and fast turnaround.',
    services_tab_all: 'All Services',
    services_tab_residency: 'Residency & Family',
    services_tab_golden: 'Golden & Investor',
    services_tab_corporate: 'Corporate & Labor',
    services_tab_typing: 'Government Typing',
    service_card_details: 'View Details',
    service_card_process_time: 'Process Time',
    service_card_govt_fee: 'Govt Fees',
    service_card_inquire: 'Inquire Now',

    // Process Section
    process_badge: 'SIMPLE 3-STEP PROCESS',
    process_title: 'How We Process Your Visa & Documents',
    process_subtitle: 'Experience a transparent, hassle-free procedure with guaranteed legal compliance from initial assessment to passport delivery.',
    process_step1_title: 'Initial Consultation & Document Audit',
    process_step1_desc: 'Submit your documents securely. Our certified legal typists audit every page against GDRFA and ICP guidelines to guarantee zero rejections.',
    process_step2_title: 'Govt Portal Typing & VIP Medical',
    process_step2_desc: 'We type your application directly on government portals and schedule your VIP medical test and biometrics with dedicated escort service.',
    process_step3_title: 'Visa Stamping & Emirates ID Delivery',
    process_step3_desc: 'Receive your official digital visa approval, physical passport stamping, and courier delivery of your newly issued Emirates ID.',
    process_cta_btn: 'Start Your Application Today',

    // Testimonials
    testimonials_badge: 'CLIENT REVIEWS',
    testimonials_title: 'Trusted by Thousands of Residents & Businesses',
    testimonials_subtitle: 'Read real experiences from families, investors, and corporate partners who relied on Brightlink for their UAE immigration journeys.',

    // FAQ
    faq_badge: 'FREQUENTLY ASKED QUESTIONS',
    faq_title: 'Got Questions? We Have Verified Answers',
    faq_subtitle: 'Find clear answers to common inquiries regarding UAE residency visas, golden visas, and government typing procedures.',

    // Contact Section
    contact_badge: 'GET IN TOUCH',
    contact_title: 'Visit Our Dubai Center or Request a Callback',
    contact_subtitle: 'Our legal typing consultants are ready to assist you in English, Arabic, Urdu, and more.',
    contact_form_name: 'Full Name',
    contact_form_name_ph: 'e.g. Alexander Wright',
    contact_form_email: 'Email Address',
    contact_form_email_ph: 'e.g. alex@company.com',
    contact_form_phone: 'Phone Number',
    contact_form_phone_ph: '+971 50 123 4567',
    contact_form_service: 'Service Needed',
    contact_form_service_select: 'Select Service Required',
    contact_form_message: 'Message / Specific Requirements',
    contact_form_message_ph: 'Please describe your visa status, family members, or business setup goals...',
    contact_form_submit: 'Send Consultation Request',
    contact_form_submitting: 'Submitting Request...',
    contact_form_success: 'Thank you! Your request has been received. Our senior legal consultant will contact you within 15 minutes.',
    contact_info_office: 'Main Office',
    contact_info_office_val: 'Al Garhoud, Near GGICO Metro Station, Deira, Dubai, UAE',
    contact_info_hours: 'Working Hours',
    contact_info_hours_val: 'Mon – Sat: 8:00 AM – 8:00 PM | Sun: Closed',
    contact_info_phone: 'Phone & WhatsApp',
    contact_info_phone_val: '+971 4 295 5588 / +971 55 968 4433',

    // Footer
    footer_tagline: 'Dubai’s most trusted government typing center and legal documentation consultancy for Golden Visas, Family Sponsorship, and Business Setup.',
    footer_col_services: 'Residency Services',
    footer_col_biz: 'Business Solutions',
    footer_col_gov: 'Govt Portals',
    footer_col_contact: 'Direct Contact',
    footer_disclaimer: 'Brightlink is an accredited private document typing and administrative consulting agency assisting clients through official UAE government portals (GDRFA, ICP, DED, MOHRE, and Dubai Courts). We are not a government agency.',
    footer_rights: 'All rights reserved. Brightlink Typing & Business Setup Services LLC.',

    // Modals
    modal_consult_title: 'Request a Free Consultation',
    modal_consult_desc: 'Speak with our senior visa consultant for immediate assistance and document evaluation.',
    modal_consult_submit: 'Confirm Consultation Request',
    modal_consult_success: 'Your consultation has been booked successfully! A representative will call you shortly.'
  },

  ar: {
    // Navigation
    nav_home: 'الرئيسية',
    nav_visa: 'التأشيرات',
    nav_services: 'الخدمات',
    nav_business_setup: 'تأسيس الشركات',
    nav_visa_check: 'فحص التأشيرة',
    nav_about: 'من نحن',
    nav_blog: 'المدونة',
    nav_contact: 'اتصل بنا',
    nav_consultation_btn: 'استشارة مجانية',
    nav_typing_sub: 'للطباعة والاستشارات',

    // Mega Dropdowns
    visa_cat_header: 'الإقامة والتأشيرات',
    services_cat_header: 'خدماتنا الحكومية',
    services_col1_header: 'خدمات التخليص والقانون',
    services_col2_header: 'العقارات والخدمات المساندة',
    services_default_title: 'دعم متخصص، في كل خطوة',
    services_default_desc: 'مساعدة موثوقة لحياتك وأعمالك في دولة الإمارات العربية المتحدة',
    services_default_btn: 'استكشف كافة الخدمات',
    biz_header: 'ابدأ رحلتك الاستثمارية والتجارية',
    biz_col_mainland: 'الشركات المحلية (البر الرئيسي)',
    biz_col_freezone: 'المناطق الحرة',
    biz_col_offshore: 'الشركات الخارجية (أوفشور)',

    // Hero Section
    hero_title_prefix: 'خدمات سريعة وموثوقة لـ',
    hero_title_highlight: 'تأشيرات وجوازات السفر',
    hero_title_suffix: 'في الإمارات',
    hero_subtitle: 'مساعدة معتمدة للحصول على الإقامة الذهبية لمدة 10 سنوات، كفالة الأسرة، الهوية الإماراتية، تجديد جواز السفر الهندي BLS، وتأسيس الشركات في دبي مع تدقيق قانوني وإنجاز في نفس اليوم.',
    hero_cta_consultation: 'احجز استشارة مجانية',
    hero_cta_calculator: 'حاسبة تكاليف التأشيرة',
    hero_stat_1_val: '+20',
    hero_stat_1_lbl: 'عاماً من الخبرة',
    hero_stat_1_desc: 'حضور راسخ وموثوق في دبي',
    hero_stat_2_val: '+10,000',
    hero_stat_2_lbl: 'عميل تم خدمتهم',
    hero_stat_2_desc: 'مقيمون، عائلات ومستثمرون دوليون',
    hero_stat_3_val: '98%',
    hero_stat_3_lbl: 'نسبة النجاح',
    hero_stat_3_desc: 'تقييم 5 نجوم لرضا العملاء',
    hero_stat_4_val: '+15',
    hero_stat_4_lbl: 'اعتمادات حكومية',
    hero_stat_4_desc: 'بوابات إقامة دبي، الهيئة، تسهيل وتوجيه',

    // About Section
    about_badge: 'عن مركز برايت لينك للطباعة',
    about_title: 'المركز الرائد لطباعة المعاملات الحكومية والتأشيرات في دبي',
    about_desc_1: 'مع أكثر من عقدين من الخدمة المتميزة في دولة الإمارات، تقدم برايت لينك خدمات طباعة وتخليص معاملات سريعة ومطابقة للأنظمة للأفراد والعائلات والشركات العالمية.',
    about_desc_2: 'يضمن ربطنا المباشر مع إقامة دبي (GDRFA)، الهيئة الاتحادية (ICP)، محاكم دبي، ووزارة الموارد البشرية (MOHRE) معالجة طلباتك دون أخطاء وبأولوية حكومية.',
    about_point_1: 'بوابة طباعة رسمية معتمدة لإقامة دبي ومراكز آمر',
    about_point_2: 'طباعة الفحص الطبي السريع VIP وبصمة الهوية الإماراتية',
    about_point_3: 'قسم متخصص لترخيص الشركات في دائرة التنمية والمناطق الحرة',
    about_point_4: 'ترجمة قانونية معتمدة من وزارة العدل وتصديق المستندات',
    about_btn_consultation: 'احجز موعد استشارة متخصصة',
    about_btn_services: 'استكشف الخدمات',

    // Services Section
    services_badge: 'خدماتنا الشاملة',
    services_title: 'حلول التأشيرات والمعاملات الحكومية المخصصة',
    services_subtitle: 'من تجديد الإقامات العائلية إلى تأشيرات المستثمر العقاري، يضمن خبراؤنا الامتثال القانوني وسرعة الإنجاز.',
    services_tab_all: 'كافة الخدمات',
    services_tab_residency: 'الإقامة والأسرة',
    services_tab_golden: 'الذهبية والمستثمر',
    services_tab_corporate: 'الشركات والعمالة',
    services_tab_typing: 'الطباعة الحكومية',
    service_card_details: 'عرض التفاصيل',
    service_card_process_time: 'مدة الإنجاز',
    service_card_govt_fee: 'الرسوم الحكومية',
    service_card_inquire: 'استفسر الآن',

    // Process Section
    process_badge: 'خطوات العمل السلسة',
    process_title: 'كيف ننجز معاملات التأشيرة والمستندات',
    process_subtitle: 'تمتع بإجراءات شفافة وخالية من المتاعب مع ضمان الامتثال القانوني الكامل من التقييم حتى استلام الإقامة.',
    process_step1_title: 'الاستشارة وتدقيق المستندات',
    process_step1_desc: 'قدم وثائقك بأمان ليقوم مستشارونا القانونيون بمراجعتها وفق اشتراطات إقامة دبي والهيئة الاتحادية لتفادي أي رفض.',
    process_step2_title: 'الطباعة الحكومية والفحص الطبي VIP',
    process_step2_desc: 'نقوم بالطباعة عبر الأنظمة الرسمية وتنسيق موعد الفحص الطبي السريع والبصمات في مراكز سمارت سالم.',
    process_step3_title: 'إصدار التأشيرة وتسليم الهوية',
    process_step3_desc: 'استلم تأشيرتك الإلكترونية فور صدورها، مع خدمة توصيل بطاقة الهوية الإماراتية المطبوعة إلى باب منزلك.',
    process_cta_btn: 'ابدأ طلبك اليوم',

    // Testimonials
    testimonials_badge: 'آراء وتقييمات العملاء',
    testimonials_title: 'موثوق من آلاف المقيمين والمستثمرين',
    testimonials_subtitle: 'اقرأ تجارب حقيقية لعملاء اعتمدوا على برايت لينك في إقامتهم وتأسيس أعمالهم في دبي.',

    // FAQ
    faq_badge: 'الأسئلة الشائعة',
    faq_title: 'لديك استفسار؟ لدينا الإجابات المعتمدة',
    faq_subtitle: 'إجابات واضحة ودقيقة لأهم التساؤلات حول الإقامة، التأشيرة الذهبية، والإجراءات الحكومية في الإمارات.',

    // Contact Section
    contact_badge: 'تواصل معنا',
    contact_title: 'تفضل بزيارة مركزنا في دبي أو اطلب اتصالاً',
    contact_subtitle: 'فريقنا المتخصص مستعد لخدمتكم بالعربية والإنجليزية والأردية ولغات متعددة.',
    contact_form_name: 'الاسم الكامل',
    contact_form_name_ph: 'مثال: محمد الشامسي',
    contact_form_email: 'البريد الإلكتروني',
    contact_form_email_ph: 'مثال: name@domain.com',
    contact_form_phone: 'رقم الهاتف / الواتساب',
    contact_form_phone_ph: '+971 50 123 4567',
    contact_form_service: 'الخدمة المطلوبة',
    contact_form_service_select: 'اختر المعاملة المطلوبة',
    contact_form_message: 'ملاحظات أو تفاصيل الطلب',
    contact_form_message_ph: 'اذكر تفاصيل التأشيرة الحالية أو عدد أفراد العائلة أو خطة العمل...',
    contact_form_submit: 'إرسال طلب الاستشارة',
    contact_form_submitting: 'جاري الإرسال...',
    contact_form_success: 'شكراً لك! تم استلام طلبك بنجاح. سيتواصل معك مستشارنا القانوني خلال 15 دقيقة.',
    contact_info_office: 'المكتب الرئيسي',
    contact_info_office_val: 'القرهود، بالقرب من محطة مترو جي جي كو، ديرة، دبي، الإمارات',
    contact_info_hours: 'ساعات العمل',
    contact_info_hours_val: 'الإثنين – السبت: 8:00 صباحاً – 8:00 مساءً | الأحد: مغلق',
    contact_info_phone: 'الهاتف والواتساب',
    contact_info_phone_val: '+971 4 295 5588 / +971 55 968 4433',

    // Footer
    footer_tagline: 'مركز الطباعة الحكومية والاستشارات القانونية الأكثر موثوقية في دبي للإقامة الذهبية وكفالة الأسرة وتأسيس الشركات.',
    footer_col_services: 'خدمات الإقامة',
    footer_col_biz: 'حلول الأعمال',
    footer_col_gov: 'البوابات الحكومية',
    footer_col_contact: 'التواصل المباشر',
    footer_disclaimer: 'برايت لينك مركز مرخص لطباعة المستندات وتقديم الاستشارات الإدارية عبر القنوات الحكومية الرسمية (إقامة دبي، الهيئة، اقتصادية دبي، وزارة العمل، ومحاكم دبي). نحن لسنا جهة حكومية.',
    footer_rights: 'جميع الحقوق محفوظة. شركة برايت لينك لخدمات الطباعة وتأسيس الأعمال ذ.م.م.',

    // Modals
    modal_consult_title: 'طلب استشارة مجانية',
    modal_consult_desc: 'تحدث مع كبير مستشاري التأشيرات للحصول على تقييم فوري وتوجيه قانوني دقيق.',
    modal_consult_submit: 'تأكيد طلب الاستشارة',
    modal_consult_success: 'تم تسجيل طلب الاستشارة بنجاح! سيتصل بك فريقنا قريباً.'
  },

  ur: {
    // Navigation
    nav_home: 'ہوم',
    nav_visa: 'ویزا',
    nav_services: 'سروسز',
    nav_business_setup: 'بزنس سیٹ اپ',
    nav_visa_check: 'ویزا چیک',
    nav_about: 'ہمارے بارے میں',
    nav_blog: 'بلاگ',
    nav_contact: 'رابطہ',
    nav_consultation_btn: 'مفت مشاورت',
    nav_typing_sub: 'ٹائپنگ اور کنسلٹنگ',

    // Mega Dropdowns
    visa_cat_header: 'رہائش اور ویزا کی سہولیات',
    services_cat_header: 'ہماری حکومتی خدمات',
    services_col1_header: 'پی آر او اور قانونی خدمات',
    services_col2_header: 'پراپرٹی اور سپورٹ سروسز',
    services_default_title: 'ہر قدم پر ماہرانہ رہنمائی',
    services_default_desc: 'متحدہ عرب امارات میں زندگی اور کاروبار کے لیے قابل اعتماد مدد',
    services_default_btn: 'تمام خدمات دیکھیں',
    biz_header: 'اپنے کاروباری سفر کا آغاز کریں',
    biz_col_mainland: 'مین لینڈ',
    biz_col_freezone: 'فری زون',
    biz_col_offshore: 'آف شور',

    // Hero Section
    hero_title_prefix: 'تیز ترین اور قابل اعتماد',
    hero_title_highlight: 'یو اے ای ویزا و پاسپورٹ',
    hero_title_suffix: 'سروسز',
    hero_subtitle: '10 سالہ گولڈن ویزا، فیملی اسپانسرشپ، امارات آئی ڈی، بی ایل ایس انڈین پاسپورٹ تجدید، اور دبئی میں بزنس سیٹ اپ کے لیے مجاز اور قانونی معاونت۔ شفاف فیس اور اسی دن پراسیسنگ۔',
    hero_cta_consultation: 'مفت مشاورت حاصل کریں',
    hero_cta_calculator: 'ویزا خرچ کیلکولیٹر',
    hero_stat_1_val: '+20',
    hero_stat_1_lbl: 'سالہ تجربہ',
    hero_stat_1_desc: 'دبئی میں تسلیم شدہ اور قابل اعتماد مقام',
    hero_stat_2_val: '+10,000',
    hero_stat_2_lbl: 'مطمئن کلائنٹس',
    hero_stat_2_desc: 'خاندان، سرمایہ کار اور کاروباری شخصیات',
    hero_stat_3_val: '98%',
    hero_stat_3_lbl: 'کامیابی کی شرح',
    hero_stat_3_desc: 'فائیو اسٹار تصدیق شدہ کسٹمر سروس',
    hero_stat_4_val: '+15',
    hero_stat_4_lbl: 'سرکاری الحاق',
    hero_stat_4_desc: 'عامر، جی ڈی آر ایف اے، آئی سی پی اور تسہیل',

    // About Section
    about_badge: 'برائٹ لنک ٹائپنگ کے بارے میں',
    about_title: 'دبئی کا سب سے مستند سرکاری ٹائپنگ اور ویزا پروسیسنگ سینٹر',
    about_desc_1: 'متحدہ عرب امارات میں دو دہائیوں سے زیادہ کے تجربے کے ساتھ، برائٹ لنک افراد، فیملیز اور ملٹی نیشنل کمپنیوں کو تیز رفتار اور قانونی ٹائپنگ خدمات فراہم کرتا ہے۔',
    about_desc_2: 'جی ڈی آر ایف اے، آئی سی پی، دبئی کورٹس اور موہرے پورٹلز کے ساتھ ہمارا براہ راست الحاق آپ کی درخواستوں میں غلطی کے امکان کو صفر بناتا ہے۔',
    about_point_1: 'جی ڈی آر ایف اے اور عامر پورٹلز کا باضابطہ ٹائپنگ سینٹر',
    about_point_2: 'وی آئی پی فاسٹ ٹریک میڈیکل فٹنس اور امارات آئی ڈی ٹائپنگ',
    about_point_3: 'دبئی ڈی ای ڈی اور تمام فری زونز کے لیے خصوصی کمپنی لائسنسنگ',
    about_point_4: 'وزارت انصاف (MOJ) سے تصدیق شدہ قانونی ترجمہ اور دستاویزات کی تصدیق',
    about_btn_consultation: 'ماہر کنسلٹنٹ سے وقت لیں',
    about_btn_services: 'خدمات کا جائزہ لیں',

    // Services Section
    services_badge: 'جامع خدمات',
    services_title: 'آپ کی ضروریات کے مطابق ویزا اور حکومتی حل',
    services_subtitle: 'فیملی رہائشی ویزا سے لے کر رئیل اسٹیٹ انویسٹر ویزا تک، ہمارے ماہرین مکمل قانونی رہنمائی اور فوری کارروائی کو یقینی بناتے ہیں۔',
    services_tab_all: 'تمام خدمات',
    services_tab_residency: 'رہائش اور فیملی',
    services_tab_golden: 'گولڈن اور انویسٹر',
    services_tab_corporate: 'کارپوریٹ اور لیبر',
    services_tab_typing: 'سرکاری ٹائپنگ',
    service_card_details: 'تفصیلات دیکھیں',
    service_card_process_time: 'دورانیہ',
    service_card_govt_fee: 'سرکاری فیس',
    service_card_inquire: 'معلومات لیں',

    // Process Section
    process_badge: 'آسان 3 مرحلہ وار عمل',
    process_title: 'ہم آپ کا ویزا اور دستاویزات کیسے پراسیس کرتے ہیں',
    process_subtitle: 'ابتدائی جانچ پڑتال سے لے کر ویزا اسٹیمپنگ تک شفاف اور پریشانی سے پاک قانونی عمل کا تجربہ کریں۔',
    process_step1_title: 'ابتدائی مشاورت اور دستاویزات کی جانچ',
    process_step1_desc: 'اپنے کاغذات محفوظ طریقے سے جمع کروائیں تاکہ ہمارے قانونی ٹائپسٹ تمام ضروریات کی تسلی کر کے ریجیکشن کو ناممکن بنا سکیں۔',
    process_step2_title: 'سرکاری پورٹل ٹائپنگ اور وی آئی پی میڈیکل',
    process_step2_desc: 'ہم پورٹل پر فورا درخواست درج کرتے ہیں اور اسمارٹ سالم میں آپ کا وی آئی پی میڈیکل اور فنگر پرنٹس شیڈول کرتے ہیں۔',
    process_step3_title: 'ویزا منظوری اور امارات آئی ڈی کی ترسیل',
    process_step3_desc: 'اپنا آفیشل ویزا حاصل کریں اور کوریئر کے ذریعے پرنٹ شدہ امارات آئی ڈی کارڈ سیدھا اپنے گھر منگوائیں۔',
    process_cta_btn: 'آج ہی درخواست شروع کریں',

    // Testimonials
    testimonials_badge: 'کلائنٹس کے تاثرات',
    testimonials_title: 'ہزاروں مطمئن شہریوں اور تاجروں کا بھروسہ',
    testimonials_subtitle: 'جانئے ان خاندانوں اور سرمایہ کاروں کی کہانیاں جنہوں نے یو اے ای میں اپنے سفر کے لیے برائٹ لنک پر اعتماد کیا۔',

    // FAQ
    faq_badge: 'عام سوالات و جوابات',
    faq_title: 'کوئی سوال ہے؟ ہمارے پاس مستند جوابات ہیں',
    faq_subtitle: 'یو اے ای ویزا قوانین، گولڈن ویزا، اور ٹائپنگ کے حوالے سے سب سے زیادہ پوچھے جانے والے سوالات۔',

    // Contact Section
    contact_badge: 'ہم سے رابطہ کریں',
    contact_title: 'دبئی آفس تشریف لائیں یا کال بیک کی درخواست کریں',
    contact_subtitle: 'ہمارے قانونی ٹائپنگ کنسلٹنٹس اردو، انگلش، عربی اور دیگر زبانوں میں رہنمائی کے لیے تیار ہیں۔',
    contact_form_name: 'پورا نام',
    contact_form_name_ph: 'مثال: محمد احمد',
    contact_form_email: 'ای میل ایڈریس',
    contact_form_email_ph: 'name@domain.com',
    contact_form_phone: 'فون / واٹس ایپ نمبر',
    contact_form_phone_ph: '+971 50 123 4567',
    contact_form_service: 'مطلوبہ سروس',
    contact_form_service_select: 'سروس منتخب کریں',
    contact_form_message: 'پیغام یا اضافی تفصیلات',
    contact_form_message_ph: 'اپنے ویزا کی موجودہ صورتحال، فیملی ممبرز، یا بزنس پلان کا ذکر کریں...',
    contact_form_submit: 'مشاورت کی درخواست بھیجیں',
    contact_form_submitting: 'بھیجا جا رہا ہے...',
    contact_form_success: 'شکریہ! آپ کی درخواست موصول ہو چکی ہے۔ ہمارا سینئر کنسلٹنٹ 15 منٹ میں رابطہ کرے گا۔',
    contact_info_office: 'مین آفس',
    contact_info_office_val: 'القرهود، جی جی آئی سی او میٹرو اسٹیشن کے قریب، دیرہ، دبئی، یو اے ای',
    contact_info_hours: 'اوقات کار',
    contact_info_hours_val: 'پیر تا ہفتہ: صبح 8:00 بجے تا رات 8:00 بجے | اتوار: بند',
    contact_info_phone: 'فون اور واٹس ایپ',
    contact_info_phone_val: '+971 4 295 5588 / +971 55 968 4433',

    // Footer
    footer_tagline: 'دبئی کا بااعتماد ترین گورنمنٹ ٹائپنگ سینٹر اور ویزا کنسلٹنسی فرم برائے گولڈن ویزا، فیملی ویزا اور بزنس سیٹ اپ۔',
    footer_col_services: 'رہائشی خدمات',
    footer_col_biz: 'بزنس سلوشنز',
    footer_col_gov: 'سرکاری پورٹلز',
    footer_col_contact: 'براہ راست رابطہ',
    footer_disclaimer: 'برائٹ لنک یو اے ای کے سرکاری پورٹلز (GDRFA, ICP, DED, MOHRE اور دبئی کورٹس) کے ذریعے ٹائپنگ اور انتظامی معاونت فراہم کرنے والی مستند نجی ایجنسی ہے۔ ہم سرکاری ادارہ نہیں ہیں۔',
    footer_rights: 'جملہ حقوق محفوظ ہیں۔ برائٹ لنک ٹائپنگ اینڈ بزنس سیٹ اپ سروسز ایل ایل سی۔',

    // Modals
    modal_consult_title: 'مفت مشاورت کی درخواست',
    modal_consult_desc: 'فوری معاونت اور دستاویزات کے جائزے کے لیے ہمارے سینئر ویزا کنسلٹنٹ سے بات کریں۔',
    modal_consult_submit: 'درخواست جمع کروائیں',
    modal_consult_success: 'آپ کی درخواست کامیابی سے موصول ہو گئی ہے۔ ہمارا نمائندہ جلد ہی رابطہ کرے گا۔'
  },

  zh: {
    nav_home: '首页',
    nav_visa: '签证',
    nav_services: '业务服务',
    nav_business_setup: '企业设立',
    nav_visa_check: '签证查询',
    nav_about: '关于我们',
    nav_blog: '博客',
    nav_contact: '联系我们',
    nav_consultation_btn: '免费咨询',
    nav_typing_sub: '政府打字与咨询',
    visa_cat_header: '居留与签证服务',
    services_cat_header: '我们的政府打字服务',
    services_col1_header: 'PRO公关与法律事务',
    services_col2_header: '房产与支持服务',
    services_default_title: '专业支持，步步相伴',
    services_default_desc: '为阿联酋的生活与商业提供全方位可靠支持',
    services_default_btn: '探索所有服务',
    biz_header: '开启您的阿联酋商业之旅',
    biz_col_mainland: '本土公司 (Mainland)',
    biz_col_freezone: '自贸区公司 (Free Zone)',
    biz_col_offshore: '离岸公司 (Offshore)',
    hero_title_prefix: '高效可靠的',
    hero_title_highlight: '阿联酋签证与护照',
    hero_title_suffix: '综合服务',
    hero_subtitle: '迪拜官方认证机构，专业协助办理10年黄金签证、家属团聚签、阿联酋身份证、BLS印度护照更换及迪拜公司设立。收费透明，加急当天递交。',
    hero_cta_consultation: '预约免费咨询',
    hero_cta_calculator: '签证费用计算器',
    hero_stat_1_val: '20+年',
    hero_stat_1_lbl: '行业丰富经验',
    hero_stat_1_desc: '深耕迪拜逾二十年',
    hero_stat_2_val: '10,000+',
    hero_stat_2_lbl: '服务客户',
    hero_stat_2_desc: '海外家庭、投资者与跨国企业',
    hero_stat_3_val: '98%',
    hero_stat_3_lbl: '签证通过率',
    hero_stat_3_desc: '五星级客户真实满意度',
    hero_stat_4_val: '15+',
    hero_stat_4_lbl: '政府官方认证',
    hero_stat_4_desc: '移民局、联邦局、劳动部直连',
    about_badge: '关于 BRIGHTLINK 打字中心',
    about_title: '迪拜领先的官方政府打字与签证审批中心',
    about_desc_1: '在阿联酋拥有二十余年的专业运营经验，Brightlink为个人、家庭和跨国公司提供合规、快速且高水准的政府事务申报服务。',
    about_desc_2: '与迪拜移民局(GDRFA)、联邦身份局(ICP)、迪拜法院及劳动部(MOHRE)的系统直连，确保您的申请零差错并享受优先审理。',
    about_point_1: 'GDRFA与Amer移民服务中心授权打字平台',
    about_point_2: 'VIP加急体检与阿联酋身份证指纹录入预约',
    about_point_3: '迪拜经济部(DED)与各大自贸区公司设立专区',
    about_point_4: '司法部(MOJ)认证法律翻译与多国使领馆公证认证',
    about_btn_consultation: '预约资深顾问咨询',
    about_btn_services: '了解全部业务',
    services_badge: '全面业务体系',
    services_title: '为您量身定制的签证与政府解决方案',
    services_subtitle: '从家属居留更新到数百万房产投资黄金签证，我们的持证专业顾问确保法律合规与极速签发。',
    services_tab_all: '全部业务',
    services_tab_residency: '居留与家属',
    services_tab_golden: '黄金签与投资者',
    services_tab_corporate: '公司劳务与执照',
    services_tab_typing: '政府政务打字',
    service_card_details: '查看详情',
    service_card_process_time: '审理周期',
    service_card_govt_fee: '政府规费',
    service_card_inquire: '立即咨询',
    process_badge: '简单3步流程',
    process_title: '我们如何协助您高效获批',
    process_subtitle: '透明、安心的标准化流程，从初审到领取居留卡，全程受到严格法律监管保护。',
    process_step1_title: '初步评估与文件严审',
    process_step1_desc: '安全提交您的材料。专业法律打字员根据移民局最新政策逐页审核，确保零拒签率。',
    process_step2_title: '政府平台申报与VIP体检',
    process_step2_desc: '直接通过政府官方系统在线申报，并为您预约专属VIP体检及快速指纹录入通道。',
    process_step3_title: '电子签证签发与实体卡递送',
    process_step3_desc: '第一时间获取官方电子居留签批文，实体身份证卡片由快递安全送达您的居住地。',
    process_cta_btn: '立即开启申请',
    testimonials_badge: '客户真实口碑',
    testimonials_title: '成千上万在阿居民与企业的信赖之选',
    testimonials_subtitle: '阅读来自不同国家的家庭、房产投资者及商业合伙人的真实合作评价。',
    faq_badge: '常见问题解答',
    faq_title: '如有疑问？为您呈现实时解答',
    faq_subtitle: '解答关于阿联酋签证规定、10年黄金签证申办及公证打字流程的常见疑虑。',
    contact_badge: '联系咨询',
    contact_title: '亲临迪拜中心或申请专属电话回访',
    contact_subtitle: '我们的法律打字顾问支持英语、阿拉伯语、中文等多语言贴心服务。',
    contact_form_name: '您的姓名',
    contact_form_name_ph: '例如：张伟',
    contact_form_email: '电子邮箱',
    contact_form_email_ph: 'zhang@example.com',
    contact_form_phone: '联系电话 / WhatsApp',
    contact_form_phone_ph: '+971 50 123 4567',
    contact_form_service: '所需服务',
    contact_form_service_select: '选择所需业务类型',
    contact_form_message: '留言或具体要求',
    contact_form_message_ph: '请简要说明您的签证状态、家庭成员情况或投资计划...',
    contact_form_submit: '发送咨询申请',
    contact_form_submitting: '正在提交...',
    contact_form_success: '感谢您的咨询！我们已收到您的申请，资深法务顾问将在15分钟内与您联系。',
    contact_info_office: '办公地址',
    contact_info_office_val: '迪拜德拉区，GGICO地铁站附近，Al Garhoud',
    contact_info_hours: '营业时间',
    contact_info_hours_val: '周一至周六: 08:00 – 20:00 | 周日: 休息',
    contact_info_phone: '电话与WhatsApp',
    contact_info_phone_val: '+971 4 295 5588 / +971 55 968 4433',
    footer_tagline: '迪拜值得信赖的官方政府打字中心与商业法律咨询机构，专业办理黄金签证、家属签证及公司注册。',
    footer_col_services: '居留签证服务',
    footer_col_biz: '商业注册方案',
    footer_col_gov: '直连政府入口',
    footer_col_contact: '直接联系',
    footer_disclaimer: 'Brightlink是一家经阿联酋官方授权的私立打字与政务咨询代理机构，通过GDRFA、ICP、DED、MOHRE及迪拜法院系统办理业务。我们非政府官方实体。',
    footer_rights: '版权所有。Brightlink Typing & Business Setup Services LLC。',
    modal_consult_title: '预约专家免费咨询',
    modal_consult_desc: '与我们的资深签证顾问即时沟通，获取权威的材料审核与方案评估。',
    modal_consult_submit: '确认提交咨询',
    modal_consult_success: '预约已成功提交！我们的顾问将尽快联系您。'
  },

  es: {
    nav_home: 'Inicio',
    nav_visa: 'Visados',
    nav_services: 'Servicios',
    nav_business_setup: 'Creación de Empresas',
    nav_visa_check: 'Verificar Visa',
    nav_about: 'Nosotros',
    nav_blog: 'Blog',
    nav_contact: 'Contacto',
    nav_consultation_btn: 'Consulta Gratuita',
    nav_typing_sub: 'Mecanografía y Consultoría',
    visa_cat_header: 'RESIDENCIA Y VISADOS',
    services_cat_header: 'NUESTROS SERVICIOS',
    services_col1_header: 'SERVICIOS PRO Y LEGALES',
    services_col2_header: 'PROPIEDAD Y SOPORTE',
    services_default_title: 'Soporte Experto en Cada Paso',
    services_default_desc: 'Asistencia confiable para su vida y negocios en los EAU',
    services_default_btn: 'Explorar Todos los Servicios',
    biz_header: 'COMIENCE SU VIAJE EMPRESARIAL',
    biz_col_mainland: 'MAINLAND',
    biz_col_freezone: 'FREE ZONE',
    biz_col_offshore: 'OFFSHORE',
    hero_title_prefix: 'Servicios Rápidos y Confiables de',
    hero_title_highlight: 'Visados y Pasaportes',
    hero_title_suffix: 'en los EAU',
    hero_subtitle: 'Asistencia autorizada para Golden Visa de 10 años, patrocinio familiar, Emirates ID y creación de empresas en Dubái con auditoría legal y presentación el mismo día.',
    hero_cta_consultation: 'Reservar Consulta Gratuita',
    hero_cta_calculator: 'Calculadora de Visas',
    hero_stat_1_val: '20+',
    hero_stat_1_lbl: 'Años de Experiencia',
    hero_stat_1_desc: 'Presencia consolidada en Dubái',
    hero_stat_2_val: '10,000+',
    hero_stat_2_lbl: 'Clientes Atendidos',
    hero_stat_2_desc: 'Familias, inversores y empresas',
    hero_stat_3_val: '98%',
    hero_stat_3_lbl: 'Tasa de Éxito',
    hero_stat_3_desc: 'Satisfacción garantizada de 5 estrellas',
    hero_stat_4_val: '15+',
    hero_stat_4_lbl: 'Acreditaciones Oficiales',
    hero_stat_4_desc: 'Portales de Inmigración y Ministerios',
    about_badge: 'ACERCA DE BRIGHTLINK TYPING',
    about_title: 'El Centro Líder de Mecanografía y Trámites de Visados en Dubái',
    about_desc_1: 'Con más de dos décadas de trayectoria en los EAU, Brightlink ofrece servicios ágiles, conformes a la ley y seguros para particulares y corporaciones.',
    about_desc_2: 'Nuestra integración directa con GDRFA, ICP y los tribunales de Dubái garantiza expedientes sin errores y con aprobaciones prioritarias.',
    about_point_1: 'Portal oficial autorizado de GDRFA y Centros Amer',
    about_point_2: 'Citas médicas VIP express y trámites de Emirates ID',
    about_point_3: 'División especializada en licencias DED y Zonas Francas',
    about_point_4: 'Traducción jurídica jurada por el Ministerio de Justicia',
    about_btn_consultation: 'Agendar Consulta Experta',
    about_btn_services: 'Explorar Servicios',
    services_badge: 'SERVICIOS INTEGRALES',
    services_title: 'Soluciones a Medida en Visados y Trámites Gubernamentales',
    services_subtitle: 'Desde renovaciones residenciales hasta visados de inversores, garantizamos total cumplimiento legal y máxima rapidez.',
    services_tab_all: 'Todos los Servicios',
    services_tab_residency: 'Residencia y Familia',
    services_tab_golden: 'Golden Visa e Inversor',
    services_tab_corporate: 'Corporativo y Laboral',
    services_tab_typing: 'Mecanografía Oficial',
    service_card_details: 'Ver Detalles',
    service_card_process_time: 'Tiempo de Trámite',
    service_card_govt_fee: 'Tasas Oficiales',
    service_card_inquire: 'Consultar Ahora',
    process_badge: 'PROCESO EN 3 PASOS',
    process_title: 'Cómo Tramitamos su Visado y Documentos',
    process_subtitle: 'Disfrute de un procedimiento claro, transparente y sin complicaciones desde la evaluación hasta la entrega final.',
    process_step1_title: 'Evaluación Inicial y Auditoría de Documentos',
    process_step1_desc: 'Envíe sus documentos de forma segura para ser revisados por nuestros especialistas y evitar rechazos.',
    process_step2_title: 'Presentación Oficial y Reconocimiento Médico VIP',
    process_step2_desc: 'Registramos su solicitud en los portales del gobierno y coordinamos su reconocimiento médico preferente.',
    process_step3_title: 'Emisión de Visado y Entrega de Emirates ID',
    process_step3_desc: 'Reciba su aprobación digital oficial y la entrega a domicilio de su tarjeta física de Emirates ID.',
    process_cta_btn: 'Iniciar Trámite Hoy',
    testimonials_badge: 'OPINIONES DE CLIENTES',
    testimonials_title: 'La Confianza de Miles de Residentes y Empresas',
    testimonials_subtitle: 'Conozca experiencias reales de familias e inversores que confiaron en Brightlink en Dubái.',
    faq_badge: 'PREGUNTAS FRECUENTES',
    faq_title: '¿Preguntas? Respuestas Verificadas y Actualizadas',
    faq_subtitle: 'Respuestas claras a las consultas más habituales sobre visados de residencia y trámites gubernamentales en los EAU.',
    contact_badge: 'CONTACTO',
    contact_title: 'Visite Nuestro Centro en Dubái o Solicite una Llamada',
    contact_subtitle: 'Nuestros consultores están a su disposición para asesorarle en múltiples idiomas.',
    contact_form_name: 'Nombre Completo',
    contact_form_name_ph: 'Ej: Carlos Mendoza',
    contact_form_email: 'Correo Electrónico',
    contact_form_email_ph: 'carlos@empresa.com',
    contact_form_phone: 'Teléfono / WhatsApp',
    contact_form_phone_ph: '+971 50 123 4567',
    contact_form_service: 'Servicio Requerido',
    contact_form_service_select: 'Seleccione un Servicio',
    contact_form_message: 'Mensaje / Detalles del Requisito',
    contact_form_message_ph: 'Describa su estatus de visa, familiares a patrocinar o planes de negocio...',
    contact_form_submit: 'Enviar Solicitud de Consulta',
    contact_form_submitting: 'Enviando...',
    contact_form_success: '¡Gracias! Hemos recibido su solicitud. Un consultor legal se comunicará con usted en 15 minutos.',
    contact_info_office: 'Oficina Principal',
    contact_info_office_val: 'Al Garhoud, cerca de la estación de metro GGICO, Deira, Dubái, EAU',
    contact_info_hours: 'Horario de Atención',
    contact_info_hours_val: 'Lun – Sáb: 8:00 AM – 8:00 PM | Dom: Cerrado',
    contact_info_phone: 'Teléfono y WhatsApp',
    contact_info_phone_val: '+971 4 295 5588 / +971 55 968 4433',
    footer_tagline: 'El centro de mecanografía gubernamental y consultoría de visados más confiable de Dubái para Golden Visa y apertura de empresas.',
    footer_col_services: 'Visados de Residencia',
    footer_col_biz: 'Soluciones de Negocio',
    footer_col_gov: 'Portales de Gobierno',
    footer_col_contact: 'Contacto Directo',
    footer_disclaimer: 'Brightlink es una agencia privada acreditada de mecanografía de documentos y consultoría que asiste a través de los portales oficiales de los EAU. No somos una entidad gubernamental.',
    footer_rights: 'Todos los derechos reservados. Brightlink Typing & Business Setup Services LLC.',
    modal_consult_title: 'Solicitar Consulta Gratuita',
    modal_consult_desc: 'Hable con nuestro consultor principal para una evaluación rápida de sus documentos.',
    modal_consult_submit: 'Confirmar Solicitud',
    modal_consult_success: '¡Consulta agendada con éxito! Nos comunicaremos con usted muy pronto.'
  },

  fr: {
    nav_home: 'Accueil',
    nav_visa: 'Visas',
    nav_services: 'Services',
    nav_business_setup: 'Création d’Entreprise',
    nav_visa_check: 'Vérifier Visa',
    nav_about: 'À Propos',
    nav_blog: 'Blog',
    nav_contact: 'Contact',
    nav_consultation_btn: 'Consultation Gratuite',
    nav_typing_sub: 'Saisie & Conseil Administratif',
    visa_cat_header: 'RÉSIDENCE ET VISAS',
    services_cat_header: 'NOS SERVICES',
    services_col1_header: 'SERVICES PRO & JURIDIQUES',
    services_col2_header: 'IMMOBILIER ET SUPPORT',
    services_default_title: 'Un Soutien Expert à Chaque Étape',
    services_default_desc: 'Une assistance de confiance pour votre vie et vos affaires aux Émirats',
    services_default_btn: 'Découvrir Tous les Services',
    biz_header: 'LANCEZ VOTRE PROJET D’ENTREPRISE',
    biz_col_mainland: 'MAINLAND',
    biz_col_freezone: 'FREE ZONE',
    biz_col_offshore: 'OFFSHORE',
    hero_title_prefix: 'Services Rapides et Fiables de',
    hero_title_highlight: 'Visas et Passeports',
    hero_title_suffix: 'aux Émirats',
    hero_subtitle: 'Accompagnement agréé pour Golden Visa 10 ans, parrainage familial, Emirates ID et création de société à Dubaï avec audit juridique et dépôt express le jour même.',
    hero_cta_consultation: 'Réserver une Consultation',
    hero_cta_calculator: 'Calculateur de Frais de Visa',
    hero_stat_1_val: '20+',
    hero_stat_1_lbl: 'Ans d’Expérience',
    hero_stat_1_desc: 'Présence solide et reconnue à Dubaï',
    hero_stat_2_val: '10 000+',
    hero_stat_2_lbl: 'Clients Accompagnés',
    hero_stat_2_desc: 'Expatriés, familles et investisseurs',
    hero_stat_3_val: '98%',
    hero_stat_3_lbl: 'Taux de Réussite',
    hero_stat_3_desc: 'Satisfaction client certifiée 5 étoiles',
    hero_stat_4_val: '15+',
    hero_stat_4_lbl: 'Accréditations d’État',
    hero_stat_4_desc: 'GDRFA, ICP, Tribunaux et Ministères',
    about_badge: 'À PROPOS DE BRIGHTLINK TYPING',
    about_title: 'Le Premier Centre de Saisie Officielle et de Visas à Dubaï',
    about_desc_1: 'Fort de plus de vingt ans d’expertise aux Émirats, Brightlink assure des démarches rapides, parfaitement conformes et sécurisées pour particuliers et entreprises.',
    about_desc_2: 'Notre liaison directe avec le GDRFA, l’ICP et les autorités judiciaires de Dubaï garantit un traitement prioritaire sans aucune erreur.',
    about_point_1: 'Portail officiel accrédité GDRFA et Centres Amer',
    about_point_2: 'Visite médicale VIP express et saisie Emirates ID',
    about_point_3: 'Département licences d’entreprises DED et Zones Franches',
    about_point_4: 'Traduction assermentée par le Ministère de la Justice',
    about_btn_consultation: 'Prendre Rendez-vous',
    about_btn_services: 'Explorer nos Services',
    services_badge: 'OFFRE COMPLÈTE',
    services_title: 'Des Solutions Visas & Administratives sur Mesure',
    services_subtitle: 'Du renouvellement de résidence au visa investisseur immobilier, nos experts vous garantissent conformité et rapidité.',
    services_tab_all: 'Tous les Services',
    services_tab_residency: 'Résidence & Famille',
    services_tab_golden: 'Golden Visa & Investisseur',
    services_tab_corporate: 'Entreprise & Emploi',
    services_tab_typing: 'Saisie Gouvernementale',
    service_card_details: 'Voir Détails',
    service_card_process_time: 'Délai d’Exécution',
    service_card_govt_fee: 'Frais Officiels',
    service_card_inquire: 'Se Renseigner',
    process_badge: 'PROCÉDURE EN 3 ÉTAPES',
    process_title: 'Comment Nous Traitons Vos Demandes',
    process_subtitle: 'Profitez d’une procédure fluide et transparente, de l’évaluation initiale jusqu’à la délivrance de vos documents.',
    process_step1_title: 'Consultation Initiale & Contrôle des Pièces',
    process_step1_desc: 'Transmettez vos pièces en toute sécurité pour un examen minutieux garantissant zéro refus administratif.',
    process_step2_title: 'Saisie sur Portails Officiels & Visite Médicale VIP',
    process_step2_desc: 'Nous enregistrons votre dossier et programmons votre bilan de santé VIP et biométrie dans les centres Smart Salem.',
    process_step3_title: 'Délivrance du Visa & Réception de l’Emirates ID',
    process_step3_desc: 'Recevez votre visa officiel en ligne et votre carte physique Emirates ID livrée directement chez vous.',
    process_cta_btn: 'Démarrer Votre Demande',
    testimonials_badge: 'TÉMOIGNAGES CLIENTS',
    testimonials_title: 'La Confiance de Milliers de Résidents et d’Entreprises',
    testimonials_subtitle: 'Découvrez les retours d’expérience de ceux qui ont choisi Brightlink pour leur installation à Dubaï.',
    faq_badge: 'QUESTIONS FRÉQUENTES',
    faq_title: 'Des Questions ? Nos Réponses Vérifiées',
    faq_subtitle: 'Retrouvez toutes les informations essentielles sur les visas de résidence et démarches administratives aux Émirats.',
    contact_badge: 'CONTACTEZ-NOUS',
    contact_title: 'Venez Nous Rendre Visite ou Demandez un Rappel',
    contact_subtitle: 'Nos consultants experts vous répondent en français, anglais, arabe et d’autres langues.',
    contact_form_name: 'Nom Complet',
    contact_form_name_ph: 'Ex: Julien Laurent',
    contact_form_email: 'Adresse Email',
    contact_form_email_ph: 'julien@domaine.com',
    contact_form_phone: 'Téléphone / WhatsApp',
    contact_form_phone_ph: '+971 50 123 4567',
    contact_form_service: 'Service Demandé',
    contact_form_service_select: 'Choisissez une prestation',
    contact_form_message: 'Précisions sur votre demande',
    contact_form_message_ph: 'Indiquez votre type de visa actuel, vos proches ou votre projet d’entreprise...',
    contact_form_submit: 'Envoyer la Demande',
    contact_form_submitting: 'Envoi en cours...',
    contact_form_success: 'Merci ! Votre demande a bien été reçue. Un conseiller vous contactera sous 15 minutes.',
    contact_info_office: 'Bureau Principal',
    contact_info_office_val: 'Al Garhoud, près du métro GGICO, Deira, Dubaï, Émirats Arabes Unis',
    contact_info_hours: 'Heures d’Ouverture',
    contact_info_hours_val: 'Lun – Sam : 08h00 – 20h00 | Dimanche : Fermé',
    contact_info_phone: 'Téléphone & WhatsApp',
    contact_info_phone_val: '+971 4 295 5588 / +971 55 968 4433',
    footer_tagline: 'Votre partenaire de confiance à Dubaï pour les visas de résidence, le Golden Visa et l’immatriculation de sociétés.',
    footer_col_services: 'Services Résidence',
    footer_col_biz: 'Création d’Entreprise',
    footer_col_gov: 'Portails d’État',
    footer_col_contact: 'Contact Direct',
    footer_disclaimer: 'Brightlink est une agence privée agréée de démarches administratives assistant ses clients sur les portails officiels des Émirats. Nous ne sommes pas une administration publique.',
    footer_rights: 'Tous droits réservés. Brightlink Typing & Business Setup Services LLC.',
    modal_consult_title: 'Demande de Consultation Gratuite',
    modal_consult_desc: 'Échangez avec notre consultant senior pour une analyse rapide de vos documents.',
    modal_consult_submit: 'Confirmer la Demande',
    modal_consult_success: 'Rendez-vous enregistré avec succès ! Nous vous recontacterons très vite.'
  },

  de: {
    nav_home: 'Startseite',
    nav_visa: 'Visa',
    nav_services: 'Dienstleistungen',
    nav_business_setup: 'Unternehmensgründung',
    nav_visa_check: 'Visa-Prüfung',
    nav_about: 'Über uns',
    nav_blog: 'Blog',
    nav_contact: 'Kontakt',
    nav_consultation_btn: 'Kostenlose Beratung',
    nav_typing_sub: 'Behördenservice & Beratung',
    visa_cat_header: 'AUFENTHALT UND VISA',
    services_cat_header: 'UNSERE SERVICES',
    services_col1_header: 'PRO & JURISTISCHE DIENSTE',
    services_col2_header: 'IMMOBILIEN & SUPPORT',
    services_default_title: 'Kompetente Betreuung bei jedem Schritt',
    services_default_desc: 'Verlässliche Unterstützung für Ihr Leben und Ihre Geschäfte in den VAE',
    services_default_btn: 'Alle Dienstleistungen ansehen',
    biz_header: 'STARTEN SIE IHR UNTERNEHMEN',
    biz_col_mainland: 'MAINLAND',
    biz_col_freezone: 'FREE ZONE',
    biz_col_offshore: 'OFFSHORE',
    hero_title_prefix: 'Schnelle & Zuverlässige',
    hero_title_highlight: 'VAE-Visa & Reisepass',
    hero_title_suffix: 'Services',
    hero_subtitle: 'Autorisierte Unterstützung für 10-Jahres-Golden-Visa, Familienvisum, Emirates ID und Unternehmensgründung in Dubai mit rechtlicher Vorprüfung und Express-Einreichung.',
    hero_cta_consultation: 'Kostenlose Beratung vereinbaren',
    hero_cta_calculator: 'Visa-Kostenrechner',
    hero_stat_1_val: '20+',
    hero_stat_1_lbl: 'Jahre Erfahrung',
    hero_stat_1_desc: 'Etablierte Präsenz in Dubai',
    hero_stat_2_val: '10.000+',
    hero_stat_2_lbl: 'Betreute Kunden',
    hero_stat_2_desc: 'Expatriates, Familien & Investoren',
    hero_stat_3_val: '98%',
    hero_stat_3_lbl: 'Erfolgsquote',
    hero_stat_3_desc: 'Verifizierte 5-Sterne-Zufriedenheit',
    hero_stat_4_val: '15+',
    hero_stat_4_lbl: 'Behördenakkreditierungen',
    hero_stat_4_desc: 'GDRFA, ICP, Ministerien & Gerichte',
    about_badge: 'ÜBER BRIGHTLINK TYPING',
    about_title: 'Dubais führendes Zentrum für Behördentyping & Visumsabwicklung',
    about_desc_1: 'Mit über zwei Jahrzehnten Erfahrung in den VAE bietet Brightlink schnelle, rechtssichere Behördendienstleistungen für Privatpersonen und Unternehmen.',
    about_desc_2: 'Unsere direkte Anbindung an Behördenportale in Dubai sorgt für fehlerfreie Bearbeitung und bevorzugte Genehmigungen.',
    about_point_1: 'Offizielles Partnerportal für GDRFA und Amer-Center',
    about_point_2: 'VIP-Express-Medizincheck & Emirates ID Erfassung',
    about_point_3: 'Spezialisierte Abteilung für DED- und Freizonen-Lizenzen',
    about_point_4: 'Beglaubigte juristische Übersetzungen & Dokumentenlegalisierung',
    about_btn_consultation: 'Beratungstermin vereinbaren',
    about_btn_services: 'Leistungen entdecken',
    services_badge: 'UMFASSENDER SERVICE',
    services_title: 'Maßgeschneiderte Visa- und Behördenlösungen',
    services_subtitle: 'Vom Familienvisum bis zum Investorenvisum garantieren unsere Spezialisten volle Rechtssicherheit und zügige Abwicklung.',
    services_tab_all: 'Alle Leistungen',
    services_tab_residency: 'Aufenthalt & Familie',
    services_tab_golden: 'Golden Visa & Investoren',
    services_tab_corporate: 'Unternehmen & Arbeit',
    services_tab_typing: 'Behördenerfassung',
    service_card_details: 'Details ansehen',
    service_card_process_time: 'Bearbeitungszeit',
    service_card_govt_fee: 'Behördengebühren',
    service_card_inquire: 'Jetzt anfragen',
    process_badge: 'EINFACHER 3-SCHRITTE-PROZESS',
    process_title: 'So bearbeiten wir Ihre Anträge',
    process_subtitle: 'Erleben Sie ein transparentes Verfahren mit garantierter Gesetzeskonformität von der Erstprüfung bis zum Visum.',
    process_step1_title: 'Erstberatung & Dokumentenprüfung',
    process_step1_desc: 'Laden Sie Ihre Unterlagen sicher hoch. Unsere Experten prüfen jedes Dokument vorab auf Einhaltung aller Vorgaben.',
    process_step2_title: 'Behördenerfassung & VIP-Gesundheitscheck',
    process_step2_desc: 'Wir erfassen Ihren Antrag direkt in den Behördensystemen und koordinieren Ihren VIP-Gesundheitstest und Biometrietag.',
    process_step3_title: 'Visumsausstellung & Zustellung der Emirates ID',
    process_step3_desc: 'Erhalten Sie Ihr digitales Visum und die bequeme Kurierzustellung Ihrer gedruckten Emirates ID Karte.',
    process_cta_btn: 'Antrag jetzt starten',
    testimonials_badge: 'KUNDENSTIMMEN',
    testimonials_title: 'Das Vertrauen tausender Einwohner und Unternehmer',
    testimonials_subtitle: 'Lesen Sie authentische Erfahrungsberichte von Familien und Investoren, die Brightlink in Dubai vertraut haben.',
    faq_badge: 'HÄUFIG GESTELLTE FRAGEN',
    faq_title: 'Haben Sie Fragen? Wir haben geprüfte Antworten',
    faq_subtitle: 'Erfahren Sie alles Wissenswerte zu Aufenthaltsvisa, dem Golden Visa und offiziellen Behördenverfahren in den VAE.',
    contact_badge: 'KONTAKT',
    contact_title: 'Besuchen Sie uns in Dubai oder fordern Sie einen Rückruf an',
    contact_subtitle: 'Unsere Berater unterstützen Sie gerne auf Deutsch, Englisch, Arabisch und weiteren Sprachen.',
    contact_form_name: 'Vollständiger Name',
    contact_form_name_ph: 'z.B. Markus Weber',
    contact_form_email: 'E-Mail-Adresse',
    contact_form_email_ph: 'markus@firma.de',
    contact_form_phone: 'Telefon / WhatsApp',
    contact_form_phone_ph: '+971 50 123 4567',
    contact_form_service: 'Gewünschter Service',
    contact_form_service_select: 'Dienstleistung auswählen',
    contact_form_message: 'Nachricht / Spezifische Anforderungen',
    contact_form_message_ph: 'Beschreiben Sie Ihren aktuellen Visa-Status oder Ihre Gründungspläne...',
    contact_form_submit: 'Beratungsanfrage absenden',
    contact_form_submitting: 'Wird gesendet...',
    contact_form_success: 'Vielen Dank! Ihre Anfrage ist eingegangen. Ein Senior-Berater wird sich innerhalb von 15 Minuten melden.',
    contact_info_office: 'Hauptbüro',
    contact_info_office_val: 'Al Garhoud, nahe Metrostation GGICO, Deira, Dubai, VAE',
    contact_info_hours: 'Öffnungszeiten',
    contact_info_hours_val: 'Mo – Sa: 08:00 – 20:00 Uhr | So: Geschlossen',
    contact_info_phone: 'Telefon & WhatsApp',
    contact_info_phone_val: '+971 4 295 5588 / +971 55 968 4433',
    footer_tagline: 'Dubais zuverlässigstes Behördenzentrum für Golden Visa, Familienaufenthalt und Unternehmensgründungen.',
    footer_col_services: 'Aufenthaltsdienste',
    footer_col_biz: 'Unternehmenslösungen',
    footer_col_gov: 'Behördenportale',
    footer_col_contact: 'Direktkontakt',
    footer_disclaimer: 'Brightlink ist eine lizenzierte private Dokumenten- und Beratungsagentur für offizielle Behördenportale der VAE. Wir sind keine staatliche Behörde.',
    footer_rights: 'Alle Rechte vorbehalten. Brightlink Typing & Business Setup Services LLC.',
    modal_consult_title: 'Kostenlose Beratung anfordern',
    modal_consult_desc: 'Sprechen Sie direkt mit unserem leitenden Visaberater zur schnellen Ersteinschätzung.',
    modal_consult_submit: 'Anfrage bestätigen',
    modal_consult_success: 'Erfolgreich gebucht! Unser Team wird Sie umgehend kontaktieren.'
  },

  ru: {
    nav_home: 'Главная',
    nav_visa: 'Визы',
    nav_services: 'Услуги',
    nav_business_setup: 'Регистрация бизнеса',
    nav_visa_check: 'Проверка визы',
    nav_about: 'О нас',
    nav_blog: 'Блог',
    nav_contact: 'Контакты',
    nav_consultation_btn: 'Бесплатная консультация',
    nav_typing_sub: 'Официальный сервис и консалтинг',
    visa_cat_header: 'РЕЗИДЕНТСТВО И ВИЗЫ',
    services_cat_header: 'НАШИ УСЛУГИ',
    services_col1_header: 'PRO И ЮРИДИЧЕСКИЕ УСЛУГИ',
    services_col2_header: 'НЕДВИЖИМОСТЬ И ПОДДЕРЖКА',
    services_default_title: 'Экспертная поддержка на каждом этапе',
    services_default_desc: 'Надежная помощь для жизни и бизнеса в Объединенных Арабских Эмиратах',
    services_default_btn: 'Все услуги центра',
    biz_header: 'ОТКРОЙТЕ СВОЙ БИЗНЕС В ДУБАЕ',
    biz_col_mainland: 'МЕЙНЛЕНД (MAINLAND)',
    biz_col_freezone: 'ФРИЗОНЫ (FREE ZONE)',
    biz_col_offshore: 'ОФШОРЫ (OFFSHORE)',
    hero_title_prefix: 'Быстрые и надежные',
    hero_title_highlight: 'Визы и Паспорта в ОАЭ',
    hero_title_suffix: 'под ключ',
    hero_subtitle: 'Официальная помощь в оформлении 10-летней Золотой визы, семейного резидентства, Emirates ID и открытии компаний в Дубае с юридическим аудитом и подачей в день обращения.',
    hero_cta_consultation: 'Записаться на консультацию',
    hero_cta_calculator: 'Калькулятор стоимости визы',
    hero_stat_1_val: '20+',
    hero_stat_1_lbl: 'Лет опыта',
    hero_stat_1_desc: 'Безупречная репутация в Дубае',
    hero_stat_2_val: '10,000+',
    hero_stat_2_lbl: 'Довольных клиентов',
    hero_stat_2_desc: 'Семьи, инвесторы и предприниматели',
    hero_stat_3_val: '98%',
    hero_stat_3_lbl: 'Успешных одобрений',
    hero_stat_3_desc: '5-звездочный рейтинг клиентского сервиса',
    hero_stat_4_val: '15+',
    hero_stat_4_lbl: 'Госаккредитаций',
    hero_stat_4_desc: 'Прямой доступ к базам GDRFA, ICP, DED',
    about_badge: 'О ЦЕНТРЕ BRIGHTLINK',
    about_title: 'Ведущий центр оформления виз и государственных услуг в Дубае',
    about_desc_1: 'Более 20 лет работая в ОАЭ, Brightlink обеспечивает быстрое, полностью соответствующее законодательству оформление документов для частных лиц и бизнеса.',
    about_desc_2: 'Прямая интеграция с иммиграционной службой Дубая (GDRFA), Федеральным органом (ICP) и судами гарантирует рассмотрение заявок без ошибок и задержек.',
    about_point_1: 'Официальный авторизованный тайпинг-центр GDRFA и Amer',
    about_point_2: 'Срочный VIP-медосмотр и сдача биометрии на Emirates ID',
    about_point_3: 'Открытие компаний в материковом Дубае (DED) и во всех СЭЗ',
    about_point_4: 'Нотариальный юридический перевод Минюста и легализация',
    about_btn_consultation: 'Консультация с юристом',
    about_btn_services: 'Каталог услуг',
    services_badge: 'КОМПЛЕКСНЫЕ РЕШЕНИЯ',
    services_title: 'Визовые и государственные услуги под любые задачи',
    services_subtitle: 'От семейного спонсорства до Золотых виз для инвесторов в недвижимость — гарантируем соблюдение регламентов и минимальные сроки.',
    services_tab_all: 'Все услуги',
    services_tab_residency: 'Резидентство и семья',
    services_tab_golden: 'Золотая виза и инвесторы',
    services_tab_corporate: 'Корпоративные и рабочие',
    services_tab_typing: 'Государственный тайпинг',
    service_card_details: 'Подробнее',
    service_card_process_time: 'Срок оформления',
    service_card_govt_fee: 'Госпошлины',
    service_card_inquire: 'Оставить заявку',
    process_badge: 'ПРОСТОЙ ПРОЦЕСС В 3 ЭТАПА',
    process_title: 'Как мы оформляем вашу визу и документы',
    process_subtitle: 'Прозрачная процедура с гарантией юридической чистоты от первой проверки документов до вручения паспорта.',
    process_step1_title: 'Консультация и аудит документов',
    process_step1_desc: 'Безопасно предоставьте документы. Наши юристы проверят каждую страницу на соответствие регламентам иммиграционной службы.',
    process_step2_title: 'Подача в госсистему и VIP-медосмотр',
    process_step2_desc: 'Мы регистрируем заявку в официальных реестрах и бронируем экспресс-медосмотр и сдачу отпечатков пальцев.',
    process_step3_title: 'Выдача визы и доставка Emirates ID',
    process_step3_desc: 'Получите электронное одобрение визы, штамп в паспорте и курьерскую доставку готовой карты Emirates ID.',
    process_cta_btn: 'Начать оформление',
    testimonials_badge: 'ОТЗЫВЫ КЛИЕНТОВ',
    testimonials_title: 'Нам доверяют тысячи экспатов и предпринимателей',
    testimonials_subtitle: 'Ознакомьтесь с реальными историями клиентов, переехавших и открывших бизнес в ОАЭ вместе с Brightlink.',
    faq_badge: 'ЧАСТО ЗАДАВАЕМЫЕ ВОПРОСЫ',
    faq_title: 'Есть вопросы? У нас есть проверенные ответы',
    faq_subtitle: 'Вся актуальная информация о получении резидентских виз, Золотой визе и правилах пребывания в Эмиратах.',
    contact_badge: 'СВЯЗАТЬСЯ С НАМИ',
    contact_title: 'Посетите наш офис в Дубае или закажите звонок',
    contact_subtitle: 'Наши консультанты свободно говорят на русском, английском, арабском и других языках.',
    contact_form_name: 'Ваше имя',
    contact_form_name_ph: 'Например: Дмитрий Смирнов',
    contact_form_email: 'Электронная почта',
    contact_form_email_ph: 'dmitry@company.com',
    contact_form_phone: 'Телефон / WhatsApp',
    contact_form_phone_ph: '+971 50 123 4567',
    contact_form_service: 'Интересующая услуга',
    contact_form_service_select: 'Выберите нужную услугу',
    contact_form_message: 'Комментарий к заявке',
    contact_form_message_ph: 'Укажите статус визы, состав семьи или цели регистрации бизнеса...',
    contact_form_submit: 'Отправить запрос',
    contact_form_submitting: 'Отправка...',
    contact_form_success: 'Спасибо! Ваша заявка принята. Ведущий юрист свяжется с вами в течение 15 минут.',
    contact_info_office: 'Главный офис',
    contact_info_office_val: 'Al Garhoud, рядом со станцией метро GGICO, Дейра, Дубай, ОАЭ',
    contact_info_hours: 'Часы работы',
    contact_info_hours_val: 'Пн – Сб: с 08:00 до 20:00 | Вс: Выходной',
    contact_info_phone: 'Телефон и WhatsApp',
    contact_info_phone_val: '+971 4 295 5588 / +971 55 968 4433',
    footer_tagline: 'Надежный государственный тайпинг-центр и юридический консалтинг в Дубае по Золотым визам, ВНЖ и открытию компаний.',
    footer_col_services: 'Визы и Резидентство',
    footer_col_biz: 'Регистрация Бизнеса',
    footer_col_gov: 'Госреестры ОАЭ',
    footer_col_contact: 'Прямая связь',
    footer_disclaimer: 'Brightlink — аккредитованное частное агентство административного и документального сопровождения через официальные госсистемы ОАЭ. Мы не являемся госорганом.',
    footer_rights: 'Все права защищены. Brightlink Typing & Business Setup Services LLC.',
    modal_consult_title: 'Бесплатная консультация',
    modal_consult_desc: 'Пообщайтесь со старшим визовым консультантом для моментального аудита ситуации.',
    modal_consult_submit: 'Подтвердить запись',
    modal_consult_success: 'Запись успешно подтверждена! Наш специалист скоро свяжется с вами.'
  },

  tr: {
    nav_home: 'Anasayfa',
    nav_visa: 'Vize',
    nav_services: 'Hizmetler',
    nav_business_setup: 'Şirket Kurulumu',
    nav_visa_check: 'Vize Kontrolü',
    nav_about: 'Hakkımızda',
    nav_blog: 'Blog',
    nav_contact: 'İletişim',
    nav_consultation_btn: 'Ücretsiz Danışmanlık',
    nav_typing_sub: 'Resmi Başvuru ve Danışmanlık',
    visa_cat_header: 'OTURUM VE VİZE İŞLEMLERİ',
    services_cat_header: 'RESMİ HİZMETLERİMİZ',
    services_col1_header: 'PRO VE HUKUKİ İŞLEMLER',
    services_col2_header: 'GAYRİMENKUL VE DESTEK',
    services_default_title: 'Her Adımda Uzman Desteği',
    services_default_desc: 'BAE’deki yaşamınız ve işiniz için güvenilir resmi danışmanlık',
    services_default_btn: 'Tüm Hizmetleri İncele',
    biz_header: 'İŞ YOLCULUĞUNUZU BAŞLATIN',
    biz_col_mainland: 'MAINLAND (ANAKARA)',
    biz_col_freezone: 'FREE ZONE (SERBEST BÖLGE)',
    biz_col_offshore: 'OFFSHORE (KIYI ÖTESİ)',
    hero_title_prefix: 'Hızlı ve Güvenilir',
    hero_title_highlight: 'BAE Vize ve Pasaport',
    hero_title_suffix: 'Hizmetleri',
    hero_subtitle: 'Dubai’de 10 Yıllık Golden Vize, Aile Sponsorluğu, Emirates ID ve Şirket Kuruluşu işlemlerinizde resmi yetkili danışmanlık. Şeffaf fiyatlandırma ve aynı gün başvuru imkanı.',
    hero_cta_consultation: 'Ücretsiz Danışmanlık Alın',
    hero_cta_calculator: 'Vize Maliyet Hesaplayıcı',
    hero_stat_1_val: '20+ Yıl',
    hero_stat_1_lbl: 'Sektör Tecrübesi',
    hero_stat_1_desc: 'Dubai’de köklü ve güvenilir varlık',
    hero_stat_2_val: '10.000+',
    hero_stat_2_lbl: 'Mutlu Müşteri',
    hero_stat_2_desc: 'Aileler, yabancı yatırımcılar ve firmalar',
    hero_stat_3_val: '%98',
    hero_stat_3_lbl: 'Başarı Oranı',
    hero_stat_3_desc: '5 yıldızlı onaylı müşteri memnuniyeti',
    hero_stat_4_val: '15+',
    hero_stat_4_lbl: 'Devlet Akreditasyonu',
    hero_stat_4_desc: 'GDRFA, ICP, DED ve Bakanlık Portalları',
    about_badge: 'BRIGHTLINK TYPING HAKKINDA',
    about_title: 'Dubai’nin Öncü Resmi Başvuru ve Vize İşlem Merkezi',
    about_desc_1: 'BAE’de yirmi yılı aşkın uzmanlığıyla Brightlink, bireylere ve kurumsal şirketlere hızlı, yasalara tam uyumlu ve güvenli resmi başvuru hizmeti sunar.',
    about_desc_2: 'Dubai Göçmenlik İdaresi (GDRFA), Federal Kimlik Kurumu (ICP) ve Mahkemeler ile doğrudan sistem bağlantımız, işlemlerinizin hatasız ve öncelikli ilerlemesini sağlar.',
    about_point_1: 'GDRFA ve Amer Merkezleri yetkili resmi işlem portalı',
    about_point_2: 'VIP express sağlık taraması ve Emirates ID parmak izi randevusu',
    about_point_3: 'Dubai DED ve tüm Serbest Bölgeler şirket lisanslama birimi',
    about_point_4: 'Adalet Bakanlığı onaylı yeminli tercüme ve evrak tasdiki',
    about_btn_consultation: 'Uzman Görüşmesi Planlayın',
    about_btn_services: 'Hizmetleri Keşfet',
    services_badge: 'KAPSAMLI ÇÖZÜMLER',
    services_title: 'İhtiyacınıza Özel Vize ve Resmi İşlem Çözümleri',
    services_subtitle: 'Aile oturum yenilemelerinden gayrimenkul yatırımcı vizelerine kadar, lisanslı uzmanlarımız hızlı ve güvenli sonuç garanti eder.',
    services_tab_all: 'Tüm Hizmetler',
    services_tab_residency: 'Oturum & Aile',
    services_tab_golden: 'Golden Vize & Yatırımcı',
    services_tab_corporate: 'Şirket & Çalışma',
    services_tab_typing: 'Resmi Yazım Hizmetleri',
    service_card_details: 'Detayları Gör',
    service_card_process_time: 'İşlem Süresi',
    service_card_govt_fee: 'Resmi Harçlar',
    service_card_inquire: 'Bilgi Alın',
    process_badge: '3 ADIMDA KOLAY SÜREÇ',
    process_title: 'Vize ve Evrak Başvurularınızı Nasıl Yönetiyoruz',
    process_subtitle: 'İlk evrak incelemesinden teslimata kadar tam şeffaf ve resmi mevzuata uygun bir süreç deneyimleyin.',
    process_step1_title: 'Ön Değerlendirme ve Evrak Denetimi',
    process_step1_desc: 'Belgelerinizi güvenle iletin. Uzmanlarımız olası bir reddi önlemek için tüm evrakları titizlikle denetler.',
    process_step2_title: 'Resmi Portala Kayıt ve VIP Sağlık Testi',
    process_step2_desc: 'Başvurunuzu anında resmi sisteme işler ve VIP sağlık kontrolü ile parmak izi randevunuzu organize ederiz.',
    process_step3_title: 'Vize Onayı ve Emirates ID Teslimatı',
    process_step3_desc: 'Dijital vize onay belgenizi alın ve basılı Emirates ID kimlik kartınızın adresinize teslim edilmesinin keyfini çıkarın.',
    process_cta_btn: 'Başvurunuzu Başlatın',
    testimonials_badge: 'MÜŞTERİ YORUMLARI',
    testimonials_title: 'Binlerce BAE Sakininin ve Şirketinin Güvendiği İsim',
    testimonials_subtitle: 'Dubai’deki vize ve şirket süreçlerinde Brightlink’i tercih edenlerin gerçek deneyimlerini okuyun.',
    faq_badge: 'SIKÇA SORULAN SORULAR',
    faq_title: 'Sorularınız mı Var? Doğrulanmış Yanıtlar Burada',
    faq_subtitle: 'BAE oturum vizeleri, Golden Vize şartları ve resmi işlemler hakkında en çok merak edilen konular.',
    contact_badge: 'İLETİŞİME GEÇİN',
    contact_title: 'Dubai Ofisimizi Ziyaret Edin veya Arama Talep Edin',
    contact_subtitle: 'Yasal danışmanlarımız Türkçe, İngilizce, Arapça ve diğer dillerde size destek vermeye hazırdır.',
    contact_form_name: 'Adınız Soyadınız',
    contact_form_name_ph: 'Örn: Ahmet Yılmaz',
    contact_form_email: 'E-posta Adresi',
    contact_form_email_ph: 'ahmet@sirket.com',
    contact_form_phone: 'Telefon / WhatsApp',
    contact_form_phone_ph: '+971 50 123 4567',
    contact_form_service: 'İlgilendiğiniz Hizmet',
    contact_form_service_select: 'Hizmet Seçiniz',
    contact_form_message: 'Mesajınız / Özel Talebiniz',
    contact_form_message_ph: 'Mevcut vize durumunuzu veya şirket kurma hedeflerinizi kısaca açıklayınız...',
    contact_form_submit: 'Danışmanlık Talebi Gönder',
    contact_form_submitting: 'Gönderiliyor...',
    contact_form_success: 'Teşekkürler! Talebiniz alındı. Kıdemli uzmanımız 15 dakika içinde sizinle iletişime geçecektir.',
    contact_info_office: 'Merkez Ofis',
    contact_info_office_val: 'Al Garhoud, GGICO Metro İstasyonu Yanı, Deira, Dubai, BAE',
    contact_info_hours: 'Çalışma Saatleri',
    contact_info_hours_val: 'Pzt – Cmt: 08:00 – 20:00 | Pazar: Kapalı',
    contact_info_phone: 'Telefon & WhatsApp',
    contact_info_phone_val: '+971 4 295 5588 / +971 55 968 4433',
    footer_tagline: 'Dubai’de Golden Vize, aile oturumu ve şirket kuruluşu süreçlerinde en güvenilir resmi işlem ve danışmanlık merkezi.',
    footer_col_services: 'Oturum Hizmetleri',
    footer_col_biz: 'İş Kurulum Çözümleri',
    footer_col_gov: 'Devlet Portalları',
    footer_col_contact: 'Doğrudan İletişim',
    footer_disclaimer: 'Brightlink, BAE resmi portalları (GDRFA, ICP, DED, MOHRE ve Dubai Mahkemeleri) üzerinden idari işlem yürüten akredite özel bir danışmanlık acentesidir. Kamu kurumu değildir.',
    footer_rights: 'Tüm hakları saklıdır. Brightlink Typing & Business Setup Services LLC.',
    modal_consult_title: 'Ücretsiz Danışmanlık Talebi',
    modal_consult_desc: 'Hızlı ön inceleme ve doğru yönlendirme için kıdemli vize uzmanımızla görüşün.',
    modal_consult_submit: 'Talebi Onayla',
    modal_consult_success: 'Talebiniz başarıyla kaydedildi! Ekibimiz en kısa sürede arayacaktır.'
  }
};

const LanguageContext = createContext(null);

export const LanguageProvider = ({ children }) => {
  const [currentLang, setCurrentLang] = useState(() => {
    try {
      const saved = localStorage.getItem('brightlink_language');
      const found = LANGUAGES.find(l => l.code === saved);
      return found ? found.code : 'en';
    } catch {
      return 'en';
    }
  });

  const languageConfig = LANGUAGES.find(l => l.code === currentLang) || LANGUAGES[0];
  const isRTL = languageConfig.dir === 'rtl';

  useEffect(() => {
    try {
      localStorage.setItem('brightlink_language', currentLang);
    } catch {}

    // Update document HTML direction and lang attribute
    document.documentElement.dir = languageConfig.dir;
    document.documentElement.lang = currentLang;

    // Optional body class for styling adjustments if needed
    if (isRTL) {
      document.body.classList.add('rtl-layout');
    } else {
      document.body.classList.remove('rtl-layout');
    }
  }, [currentLang, languageConfig, isRTL]);

  const setLanguage = (code) => {
    const valid = LANGUAGES.some(l => l.code === code);
    if (valid) {
      setCurrentLang(code);
    }
  };

  const t = (key, fallback = '') => {
    const langDict = TRANSLATIONS[currentLang];
    if (langDict && langDict[key]) {
      return langDict[key];
    }
    // Fallback to English
    if (TRANSLATIONS.en && TRANSLATIONS.en[key]) {
      return TRANSLATIONS.en[key];
    }
    return fallback || key;
  };

  const tItem = (title) => {
    if (!title) return '';
    if (currentLang === 'en') return title;
    const itemDict = ITEM_TRANSLATIONS[title];
    if (itemDict && itemDict[currentLang]) {
      return itemDict[currentLang];
    }
    return title;
  };

  return (
    <LanguageContext.Provider
      value={{
        currentLanguage: currentLang,
        languageConfig,
        languages: LANGUAGES,
        setLanguage,
        isRTL,
        dir: languageConfig.dir,
        t,
        tItem
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const ITEM_TRANSLATIONS = {
  'Family Visa Sponsorship': {
    ar: 'كفالة تأشيرة الأسرة',
    ur: 'فیملی ویزا اسپانسرشپ',
    zh: '家属团聚居留签证',
    es: 'Patrocinio de Visa Familiar',
    fr: 'Parrainage de Visa Familial',
    de: 'Familienvisum-Sponsoring',
    ru: 'Спонсорство семейной визы',
    tr: 'Aile Vizesi Sponsorluğu'
  },
  'Family Visa': {
    ar: 'تأشيرة الأسرة',
    ur: 'فیملی ویزا',
    zh: '家属签证',
    es: 'Visa Familiar',
    fr: 'Visa Familial',
    de: 'Familienvisum',
    ru: 'Семейная виза',
    tr: 'Aile Vizesi'
  },
  'UAE Golden Visa (10-Yr)': {
    ar: 'التأشيرة الذهبية للإمارات (10 سنوات)',
    ur: 'یو اے ای گولڈن ویزا (10 سالہ)',
    zh: '阿联酋黄金签证 (10年)',
    es: 'UAE Golden Visa (10 Años)',
    fr: 'Golden Visa EAU (10 Ans)',
    de: 'VAE Golden Visa (10 Jahre)',
    ru: 'Золотая виза ОАЭ (10 лет)',
    tr: 'BAE Golden Vizesi (10 Yıl)'
  },
  'Golden Visa': {
    ar: 'التأشيرة الذهبية',
    ur: 'گولڈن ویزا',
    zh: '黄金签证',
    es: 'Golden Visa',
    fr: 'Golden Visa',
    de: 'Golden Visa',
    ru: 'Золотая виза',
    tr: 'Golden Vize'
  },
  'Property Investor Visa': {
    ar: 'تأشيرة المستثمر العقاري',
    ur: 'پراپرٹی انویسٹر ویزا',
    zh: '房产投资者签证',
    es: 'Visa de Inversor Inmobiliario',
    fr: 'Visa Investisseur Immobilier',
    de: 'Immobilien-Investorenvisum',
    ru: 'Виза инвестора в недвижимость',
    tr: 'Gayrimenkul Yatırımcı Vizesi'
  },
  'Property Visa': {
    ar: 'تأشيرة عقار',
    ur: 'پراپرٹی ویزا',
    zh: '房产签证',
    es: 'Visa de Propiedad',
    fr: 'Visa Propriété',
    de: 'Immobilienvisum',
    ru: 'Виза на недвижимость',
    tr: 'Gayrimenkul Vizesi'
  },
  'Investor & Partner Visa': {
    ar: 'تأشيرة المستثمر والشريك',
    ur: 'انویسٹر اور پارٹنر ویزا',
    zh: '公司合伙人与投资人签证',
    es: 'Visa de Inversor y Socio',
    fr: 'Visa Investisseur & Associé',
    de: 'Investoren- & Partner-Visum',
    ru: 'Виза инвестора и партнера',
    tr: 'Yatırımcı ve Ortak Vizesi'
  },
  'Investor Visa': {
    ar: 'تأشيرة مستثمر',
    ur: 'انویسٹر ویزا',
    zh: '投资人签证',
    es: 'Visa de Inversor',
    fr: 'Visa Investisseur',
    de: 'Investorenvisum',
    ru: 'Виза инвестора',
    tr: 'Yatırımcı Vizesi'
  },
  'Newborn Baby Visa': {
    ar: 'تأشيرة المولود الجديد',
    ur: 'نوزائیدہ بچے کا ویزا',
    zh: '新生儿居留登记',
    es: 'Visa para Recién Nacido',
    fr: 'Visa Nouveau-Né',
    de: 'Neugeborenen-Visum',
    ru: 'Виза для новорожденного',
    tr: 'Yeni Doğan Bebek Vizesi'
  },
  'Newborn Visa': {
    ar: 'تأشيرة مولود',
    ur: 'نوزائیدہ ویزا',
    zh: '新生儿签证',
    es: 'Visa Recién Nacido',
    fr: 'Visa Nouveau-Né',
    de: 'Neugeborenen-Visum',
    ru: 'Виза новорожденного',
    tr: 'Yeni Doğan Vizesi'
  },
  'Domestic Worker & Maid Visa': {
    ar: 'تأشيرة العمالة المساعدة والمدبرة',
    ur: 'گھریلو ملازمہ / میڈ ویزا',
    zh: '家政雇佣与管家签证',
    es: 'Visa de Empleada del Hogar',
    fr: 'Visa Employé de Maison',
    de: 'Hausangestellten-Visum',
    ru: 'Виза для домашнего персонала',
    tr: 'Ev Hizmetlisi ve Yardımcı Vizesi'
  },
  'Maid Visa': {
    ar: 'تأشيرة مساعدة منزلية',
    ur: 'میڈ ویزا',
    zh: '家政保姆签',
    es: 'Visa de Empleada',
    fr: 'Visa Employé',
    de: 'Hausangestelltenvisum',
    ru: 'Виза для помощницы',
    tr: 'Ev Hizmetlisi Vizesi'
  },
  'Tourist & Visit Visa': {
    ar: 'تأشيرة السياحة والزيارة',
    ur: 'ٹورسٹ اور وزٹ ویزا',
    zh: '旅游与探亲商务签证',
    es: 'Visa de Turista y Visita',
    fr: 'Visa Touriste & Visite',
    de: 'Touristen- & Besuchsvisum',
    ru: 'Туристическая и гостевая виза',
    tr: 'Turistik ve Ziyaret Vizesi'
  },
  'Tourist Visa': {
    ar: 'تأشيرة سياحة',
    ur: 'ٹورسٹ ویزا',
    zh: '旅游签证',
    es: 'Visa de Turista',
    fr: 'Visa Touriste',
    de: 'Touristenvisum',
    ru: 'Туристическая виза',
    tr: 'Turist Vizesi'
  },
  'Virtual Work & Nomad Visa': {
    ar: 'تأشيرة العمل الافتراضي والرحالة',
    ur: 'ورچوئل ورک اور نومڈ ویزا',
    zh: '远程工作与数字游民签证',
    es: 'Visa de Trabajo Virtual y Nómada',
    fr: 'Visa Travail Virtuel & Nomade',
    de: 'Virtuelles Arbeits- & Nomad-Visum',
    ru: 'Виза цифрового кочевника',
    tr: 'Uzaktan Çalışma ve Göçebe Vizesi'
  },
  'Virtual Work Visa': {
    ar: 'تأشيرة العمل الافتراضي',
    ur: 'ورچوئل ورک ویزا',
    zh: '远程工作签证',
    es: 'Visa Trabajo Virtual',
    fr: 'Visa Travail Virtuel',
    de: 'Virtuelles Arbeitsvisum',
    ru: 'Виза удаленной работы',
    tr: 'Uzaktan Çalışma Vizesi'
  },
  'Professional License': {
    ar: 'رخصة مهنية',
    ur: 'پروفیشنل لائسنس',
    zh: '专业服务牌照',
    es: 'Licencia Profesional',
    fr: 'Licence Professionnelle',
    de: 'Berufslizenz',
    ru: 'Профессиональная лицензия',
    tr: 'Mesleki Lisans'
  },
  'LLC Company': {
    ar: 'شركة ذات مسؤولية محدودة',
    ur: 'ایل ایل سی کمپنی',
    zh: '有限责任公司 (LLC)',
    es: 'Empresa LLC',
    fr: 'Société LLC',
    de: 'LLC-Gesellschaft',
    ru: 'Компания LLC',
    tr: 'LLC Şirketi'
  },
  'Branch / Representative Office': {
    ar: 'فرع شركة / مكتب تمثيل',
    ur: 'برانچ یا نمائندہ دفتر',
    zh: '分公司 / 代表处',
    es: 'Sucursal / Oficina de Representación',
    fr: 'Succursale / Bureau de Représentation',
    de: 'Zweigniederlassung / Repräsentanz',
    ru: 'Филиал / Представительство',
    tr: 'Şube / Temsilcilik Ofisi'
  },
  'Dubai Free Zone': {
    ar: 'منطقة دبي الحرة',
    ur: 'دبئی فری زون',
    zh: '迪拜自贸区',
    es: 'Zona Franca de Dubái',
    fr: 'Zone Franche de Dubaï',
    de: 'Dubai Freezone',
    ru: 'СЭЗ Дубая',
    tr: 'Dubai Serbest Bölgesi'
  },
  'Abu Dhabi Free Zone': {
    ar: 'منطقة أبوظبي الحرة',
    ur: 'ابوظہبی فری زون',
    zh: '阿布扎比自贸区',
    es: 'Zona Franca de Abu Dabi',
    fr: 'Zone Franche d’Abou Dabi',
    de: 'Abu Dhabi Freezone',
    ru: 'СЭЗ Абу-Даби',
    tr: 'Abu Dabi Serbest Bölgesi'
  },
  'Sharjah Free Zone': {
    ar: 'منطقة الشارقة الحرة',
    ur: 'شارجہ فری زون',
    zh: '沙迦自贸区',
    es: 'Zona Franca de Sharjah',
    fr: 'Zone Franche de Sharjah',
    de: 'Sharjah Freezone',
    ru: 'СЭЗ Шарджи',
    tr: 'Sharjah Serbest Bölgesi'
  },
  'Ajman Free Zone': {
    ar: 'منطقة عجمان الحرة',
    ur: 'عجمان فری زون',
    zh: '阿治曼自贸区',
    es: 'Zona Franca de Ajman',
    fr: 'Zone Franche d’Ajman',
    de: 'Ajman Freezone',
    ru: 'СЭЗ Аджмана',
    tr: 'Ajman Serbest Bölgesi'
  },
  'Fujairah Free Zone': {
    ar: 'منطقة الفجيرة الحرة',
    ur: 'فجیرہ فری زون',
    zh: '富查伊拉自贸区',
    es: 'Zona Franca de Fujairah',
    fr: 'Zone Franche de Fujairah',
    de: 'Fujairah Freezone',
    ru: 'СЭЗ Фуджейры',
    tr: 'Fujairah Serbest Bölgesi'
  },
  'RAK Free Zone': {
    ar: 'منطقة رأس الخيمة الحرة',
    ur: 'راس الخیمہ فری زون',
    zh: '哈伊马角自贸区',
    es: 'Zona Franca de RAK',
    fr: 'Zone Franche de RAK',
    de: 'RAK Freezone',
    ru: 'СЭЗ Рас-эль-Хаймы',
    tr: 'RAK Serbest Bölgesi'
  },
  'UAQ Free Zone': {
    ar: 'منطقة أم القيوين الحرة',
    ur: 'ام القیوین فری زون',
    zh: '乌姆盖万自贸区',
    es: 'Zona Franca de UAQ',
    fr: 'Zone Franche d’UAQ',
    de: 'UAQ Freezone',
    ru: 'СЭЗ Умм-эль-Кайвайна',
    tr: 'UAQ Serbest Bölgesi'
  },
  'All Free Zones': {
    ar: 'جميع المناطق الحرة',
    ur: 'تمام فری زونز',
    zh: '所有自贸区',
    es: 'Todas las Zonas Francas',
    fr: 'Toutes les Zones Franches',
    de: 'Alle Freizonen',
    ru: 'Все свободные зоны',
    tr: 'Tüm Serbest Bölgeler'
  },
  'RAK Offshore': {
    ar: 'أوفشور رأس الخيمة',
    ur: 'آر اے کے آف شور',
    zh: '哈伊马角离岸 (RAK Offshore)',
    es: 'RAK Offshore',
    fr: 'RAK Offshore',
    de: 'RAK Offshore',
    ru: 'Офшор RAK',
    tr: 'RAK Offshore'
  },
  'JAFZA Offshore': {
    ar: 'أوفشور جافزا',
    ur: 'جافزا آف شور',
    zh: '杰贝阿里离岸 (JAFZA Offshore)',
    es: 'JAFZA Offshore',
    fr: 'JAFZA Offshore',
    de: 'JAFZA Offshore',
    ru: 'Офшор JAFZA',
    tr: 'JAFZA Offshore'
  },
  'Ajman Offshore': {
    ar: 'أوفشور عجمان',
    ur: 'عجمان آف شور',
    zh: '阿治曼离岸 (Ajman Offshore)',
    es: 'Ajman Offshore',
    fr: 'Ajman Offshore',
    de: 'Ajman Offshore',
    ru: 'Офшор Аджмана',
    tr: 'Ajman Offshore'
  },
  'PRO Services': {
    ar: 'خدمات التعقيب الحكومي',
    ur: 'پی آر او سروسز',
    zh: 'PRO政企公关服务',
    es: 'Servicios PRO',
    fr: 'Services PRO',
    de: 'PRO-Dienstleistungen',
    ru: 'Услуги PRO',
    tr: 'PRO Hizmetleri'
  },
  'Emirates ID': {
    ar: 'الهوية الإماراتية',
    ur: 'امارات آئی ڈی',
    zh: '阿联酋身份证 (EID)',
    es: 'Emirates ID',
    fr: 'Emirates ID',
    de: 'Emirates ID',
    ru: 'Emirates ID',
    tr: 'Emirates ID'
  },
  'Amer Center': {
    ar: 'خدمات مركز آمر',
    ur: 'عامر سینٹر',
    zh: 'Amer移民服务中心',
    es: 'Centro Amer',
    fr: 'Centre Amer',
    de: 'Amer-Zentrum',
    ru: 'Центр Amer',
    tr: 'Amer Merkezi'
  },
  'Tasheel Services': {
    ar: 'خدمات تسهيل (العمل)',
    ur: 'تسہیل سروسز',
    zh: 'Tasheel劳动部服务',
    es: 'Servicios Tasheel',
    fr: 'Services Tasheel',
    de: 'Tasheel-Services',
    ru: 'Услуги Tasheel',
    tr: 'Tasheel Hizmetleri'
  },
  'Tawjeeh Services': {
    ar: 'خدمات توجيه',
    ur: 'توجیہ سروسز',
    zh: 'Tawjeeh劳工指引',
    es: 'Servicios Tawjeeh',
    fr: 'Services Tawjeeh',
    de: 'Tawjeeh-Services',
    ru: 'Услуги Tawjeeh',
    tr: 'Tawjeeh Hizmetleri'
  },
  'Document Attestation': {
    ar: 'تصديق المستندات والشهادات',
    ur: 'دستاویزات کی تصدیق',
    zh: '文件公证双认证',
    es: 'Apostilla y Legalización',
    fr: 'Attestation de Documents',
    de: 'Dokumentenbeglaubigung',
    ru: 'Легализация документов',
    tr: 'Evrak Tasdik İşlemleri'
  },
  'Legal Translation': {
    ar: 'الترجمة القانونية المعتمدة',
    ur: 'قانونی ترجمہ',
    zh: '司法部认证法律翻译',
    es: 'Traducción Jurada',
    fr: 'Traduction Juridique',
    de: 'Beglaubigte Übersetzung',
    ru: 'Нотариальный перевод',
    tr: 'Yeminli Tercüme'
  },
  'Notary Services': {
    ar: 'خدمات الكاتب العدل',
    ur: 'نوٹری سروسز',
    zh: '法院公证人认证',
    es: 'Servicios Notariales',
    fr: 'Services Notariés',
    de: 'Notariatsdienste',
    ru: 'Нотариальные услуги',
    tr: 'Noter Hizmetleri'
  },
  'Wills & Testament': {
    ar: 'تسجيل الوصايا والتركات',
    ur: 'وصیت کا اندراج',
    zh: '遗嘱公证与信托',
    es: 'Testamentos y Sucesiones',
    fr: 'Testaments & Successions',
    de: 'Testamente & Nachlass',
    ru: 'Оформление завещаний',
    tr: 'Vasiyetname İşlemleri'
  },
  'DLD Trustee Services': {
    ar: 'أمين التسجيل العقاري (DLD)',
    ur: 'ڈی ایل ڈی ٹرسٹیز سروسز',
    zh: '土地局(DLD)房产信托',
    es: 'Fideicomiso DLD',
    fr: 'Services DLD Trustee',
    de: 'DLD Trustee Services',
    ru: 'Трастовые услуги DLD',
    tr: 'DLD Gayrimenkul Emaneti'
  },
  'RERA License Dubai': {
    ar: 'ترخيص ريرا للوساطة العقارية',
    ur: 'ریرا لائسنس دبئی',
    zh: 'RERA房产经纪资质',
    es: 'Licencia RERA Dubái',
    fr: 'Licence RERA Dubaï',
    de: 'RERA-Lizenz Dubai',
    ru: 'Лицензия RERA в Дубае',
    tr: 'RERA Lisansı Dubai'
  },
  'Property Revaluation': {
    ar: 'التقييم العقاري المعتمد',
    ur: 'پراپرٹی ری ویلیوایشن',
    zh: '官方房产重估报告',
    es: 'Revalorización de Propiedades',
    fr: 'Réévaluation Immobilière',
    de: 'Immobilienneubewertung',
    ru: 'Оценка недвижимости',
    tr: 'Gayrimenkul Değerleme'
  },
  "Driver's License in the UAE": {
    ar: 'استبدال رخصة القيادة في الإمارات',
    ur: 'ڈرائیونگ لائسنس کا تبادلہ',
    zh: '阿联酋驾照直接换领',
    es: 'Canje de Carnet de Conducir',
    fr: 'Permis de Conduire aux Émirats',
    de: 'Führerscheinumtausch in den VAE',
    ru: 'Обмен водительских прав в ОАЭ',
    tr: 'BAE Sürücü Belgesi Değişimi'
  },
  'Medical & EID': {
    ar: 'الفحص الطبي والهوية VIP',
    ur: 'میڈیکل اور امارات آئی ڈی',
    zh: 'VIP快捷体检与指纹',
    es: 'Médico y Emirates ID',
    fr: 'Visite Médicale & EID',
    de: 'Medizincheck & Emirates ID',
    ru: 'Медосмотр и Emirates ID',
    tr: 'Sağlık Testi ve EID'
  },
  'Visa Validity Checker': {
    ar: 'فحص صلاحية الإقامة والغرامات',
    ur: 'ویزا ویلیڈیٹی چیکر',
    zh: '签证有效期与离境审查',
    es: 'Verificador de Validez de Visa',
    fr: 'Vérificateur de Validité de Visa',
    de: 'Visa-Gültigkeitsprüfung',
    ru: 'Проверка статуса визы',
    tr: 'Vize Geçerlilik Kontrolü'
  },
  'ILOE Insurance': {
    ar: 'التأمين ضد التعطل عن العمل (ILOE)',
    ur: 'بے روزگاری انشورنس (ILOE)',
    zh: '强制失业保险 (ILOE)',
    es: 'Seguro de Desempleo ILOE',
    fr: 'Assurance Chômage ILOE',
    de: 'ILOE-Arbeitslosenversicherung',
    ru: 'Страховка от безработицы ILOE',
    tr: 'ILOE İşsizlik Sigortası'
  },
  'Product Registration': {
    ar: 'تسجيل المنتجات في البلدية',
    ur: 'پروڈکٹ رجسٹریشن',
    zh: '市政厅产品注册备案 (Montaji)',
    es: 'Registro de Productos',
    fr: 'Enregistrement de Produits',
    de: 'Produktregistrierung',
    ru: 'Регистрация продукции',
    tr: 'Ürün Tescil İşlemleri'
  }
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    // Return sensible fallback if used outside provider
    return {
      currentLanguage: 'en',
      languageConfig: LANGUAGES[0],
      languages: LANGUAGES,
      setLanguage: () => {},
      isRTL: false,
      dir: 'ltr',
      t: (key, fallback = '') => fallback || key
    };
  }
  return context;
};

export default LanguageContext;
